baseURL = "https://bikesontrains.com/"
languageCode = "en-us"
title = "BikesOnTrains"
theme = "soho"

[params]
author = "Heidi and Phil"

## Set one of:
# gravatar = "soho@example.com"
# profilePicture = "images/profile.png"

copyright = "Heidi and Phil"

## Set custom theme color.
# themeColor = "lightblue"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/jungledev/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/heidihansen/bikesontrains"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/jungledev"

[menu]

  [[menu.main]]
    name = "Netherlands"
    weight = 100
    identifier = "netherlands"
    url = "/countries/netherlands/"

  [[menu.main]]
    name = "Belgium"
    weight = 100
    identifier = "belgium"
    url = "/countries/belgium/"

  [[menu.main]]
    name = "France"
    weight = 100
    identifier = "france"
    url = "/countries/france/"

  [[menu.main]]
    name = "Morocco"
    weight = 100
    identifier = "morocco"
    url = "/countries/morocco/"

  [[menu.main]]
    name = "Spain"
    weight = 100
    identifier = "spain"
    url = "/countries/spain/"

  [[menu.main]]
    name = "United Kingom"
    weight = 100
    identifier = "uk"
    url = "/countries/uk/"
